config/routes.rb
Rails.application.routes.draw do

  resources :register_app
  
  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'users/signout', to: 'devise/sessions#destroy'
  
  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/register_app.rb
class RegisterApp < ActiveRecord::Base
    belongs_to :user
    has_many :events, dependent: :destroy
end

app/controllers/register_app_controller.rb
class RegisterAppController < ApplicationController
  def index
    @register_apps = RegisterApp.all
  end

  def show
    @register_app = RegisterApp.find(params[:id])
    @events = @register_app.events.group_by(&:name)
  end

  def new
    @register_app = RegisterApp.new
  end

  def create
    @register_app = RegisterApp.new
    @register_app.name = params[:register_app][:name]
    @register_app.url = params[:register_app][:url]
    @register_app.user_id = current_user.id
    
    if @register_app.save
      redirect_to @register_app, notice: "Your App has been assimilated into the system"
    else
      flash.now[:alert] = "Error! Error! Error! Umm, that didn't work"
      render :new
    end
  end

  def edit
    @register_app = RegisterApp.find(params[:id])
  end

  def update
    @register_app = RegisterApp.find(params[:id])
    @register_app.name = params[:register_app][:name]
    @register_app.url = params[:register_app][:url]
    
    if @register_app.save
      flash[:notice] = "Change is good, it's like a whole new App"
      redirect_to @register_app
    else
      flash.now[:alert] = "Error! Error! Error! Umm, that didn't work"
      render :edit
    end
  end

  def destroy
    @register_app = RegisterApp.find(params[:id])
    
    if @register_app.destroy
      flash[:notice] = "#{@register_app.name} has outlived its usefulness. It's gone now"
      redirect_to action: :index
    else
      flash.now[:alert] = "Error! Error! Error! Umm, that didn't work"
      render :show
    end
  end
end

app/helpers/register_app_helper.rb
module RegisterAppHelper
end

app/views/register_app/create.html.erb
<h1>RegisterApp#create</h1>
<p>Find me in app/views/register_app/create.html.erb</p>

app/views/register_app/destroy.html.erb
<h1>RegisterApp#destroy</h1>
<p>Find me in app/views/register_app/destroy.html.erb</p>

app/views/register_app/edit.html.erb
<h1>Edit Application</h1>
<div class="row">
    <div class="col-md-8">
        <%= form_for @register_app do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control', placeholder: "What's the App's name?" %>
            </div>
            <div class="form-group">
                <%= f.label :url %>
                <%= f.text_field :url, class: 'form-control', placeholder: "and what is the URL?" %>
            </div>
                <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
    </div>
</div>

app/views/register_app/index.html.erb
<h1>Registered Applications</h1>
 <div class="col-md-4">
 <%= link_to "Add an App", new_register_app_path, class: 'btn btn-xs btn-success' %>
 </div>
<br>
<div class="row">
 <div class="col-md-8">
  <% @register_apps.each do |register_app| %>
   <div class="media">
    <div class="media-body">
     <h4 class="media-heading">
        <% if register_app.user_id == current_user.id %>
             <li><%= link_to register_app.name, register_app %></li>
        <% end %>
     </h4>
    </div>
   </div>
  <% end %>
 </div>
</div>

app/views/register_app/new.html.erb
 <h1>New Application</h1>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @register_app, :url => register_app_index_path do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: "What's the App's name?" %>
        </div>
        <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url, class: 'form-control', placeholder: "and what is the URL?" %>
        </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/register_app/show.html.erb
<h1><%= @register_app.name %> - 
<div class="btn-group">
    <%= link_to "Edit", edit_register_app_path, class: 'btn btn-xs btn-success' %>
    <%= link_to "Delete", @register_app, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'What did this App ever do to you? Are you sure?' } %>
</div></h1>
<br>

<div class="row">
    <br>
    <div class ="col-md-3">
       <h4><%= @register_app.url %></h4> 
    </div>
    <br>
    <div class ="col-md-9">
        <% @events.each do |name, events| %>
        <li><%= name %> --> # of occurances <%= events.count %></li> 
        <%= pie_chart @register_app.events.group(:name).count %>
        <%= line_chart @register_app.events.group_by_day(:created_at).count %>
        <% end %>
    </div>
</div>

app/views/register_app/update.html.erb
<h1>RegisterApp#update</h1>
<p>Find me in app/views/register_app/update.html.erb</p>